# ============================================================
# Name: verify-v3-ai-base-controlled-start.py
# Purpose: Verify the v3 Ollama and Redis base service configuration and latest startup report.
# Trigger: python 验证智能底座受控启动.py
# Owner system: 01 core system.
# Dependencies: Python 3 standard library; Docker reports generated by 执行智能底座受控启动.ps1.
# Safety: Read-only verification. Does not start, stop, delete, send messages, write old system data, or call broker APIs/trading.
# Change log: 2026-04-28 created v3 AI base verification script.
# ============================================================

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(r"D:\杰哥智能化系统\01杰哥智能系统")
COMPOSE = ROOT / "01配置" / "docker-compose.智能底座.yml"
LATEST = ROOT / "04日志" / "智能底座" / "v3-ai-base-controlled-start-latest.json"


def fail(message: str) -> None:
    print(json.dumps({"ok": False, "message": message}, ensure_ascii=False, indent=2))
    raise SystemExit(1)


def main() -> None:
    checks: list[dict[str, object]] = []

    if not COMPOSE.exists():
        fail(f"compose missing: {COMPOSE}")

    text = COMPOSE.read_text(encoding="utf-8")
    required_tokens = [
        "container_name: jiege_v3_ollama",
        "container_name: jiege_v3_redis",
        "127.0.0.1:29134:11434",
        "127.0.0.1:26379:6379",
        "../03数据/ollama:/root/.ollama",
        "../03数据/redis:/data",
    ]
    forbidden_tokens = [
        "D:\\杰哥智能体操作系统",
        "D:\\01杰哥智能系统",
        "docker rm",
        "Remove-Item",
        "rm -rf",
        "docker volume rm",
    ]

    for token in required_tokens:
        checks.append({"name": f"required token: {token}", "ok": token in text})

    for token in forbidden_tokens:
        checks.append({"name": f"forbidden token absent: {token}", "ok": token not in text})

    if LATEST.exists():
        report = json.loads(LATEST.read_text(encoding="utf-8-sig"))
        checks.append({"name": "latest report ok", "ok": report.get("ok") is True})
        checks.append({"name": "no old jiege service stop", "ok": report.get("safety", {}).get("old_jiege_service_stop") is False})
        checks.append({"name": "no wework send", "ok": report.get("safety", {}).get("wework_send") is False})
        checks.append({"name": "no auto trade", "ok": report.get("safety", {}).get("auto_trade") is False})
    else:
        checks.append({"name": "latest report not required before first startup", "ok": True})

    ok = all(item["ok"] for item in checks)
    result = {
        "ok": ok,
        "passed": sum(1 for item in checks if item["ok"]),
        "total": len(checks),
        "checks": checks,
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    if not ok:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
